"""Updated models for Product, Store, and Audit

Revision ID: 8cba1f54cc2c
Revises: 1e5562f2bf3c
Create Date: 2024-09-18 10:23:46.557683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cba1f54cc2c'
down_revision: Union[str, None] = '1e5562f2bf3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
